USE results_db;
DROP TABLE IF EXISTS results_table;

CREATE TABLE results_table (
  id INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id),
  Pred VARCHAR(255) NOT NULL,
  Suggestion      VARCHAR(255) NOT NULL,
  Date     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
