USE `results_db`;
DROP TABLE IF EXISTS `ADVICES`;
CREATE TABLE `ADVICES` (
	`AIP_ADV_PK_ID` INT NOT NULL AUTO_INCREMENT,
	`AIP_ADV_DATETIME` DATETIME NULL,
	`AIP_ADV_ADVICE` NVARCHAR(4000) NULL,
	`AIP_ADV_PARAM_PROPOSED_VALUE` NVARCHAR(4000) NULL,
	`AIP_ADV_PARAM_OLD_VALUE` NVARCHAR(4000) NULL,
	`AIP_ADV_PARAM_NAME` NVARCHAR(4000) NULL,
	PRIMARY KEY (`AIP_ADV_PK_ID`)
);

USE `results_db`;
DROP TABLE IF EXISTS `CANCELLEDACTIONS`;
CREATE TABLE `CANCELLEDACTIONS`(
	`AIC_PARAM_ACT_PK_ID` INT NOT NULL AUTO_INCREMENT,
	`AIC_PARAM_ADV_PK_ID` INT NULL,
	`AIC_PARAM_ADVICE` NVARCHAR(4000) NULL,
	`AIC_PARAM_NAME` NVARCHAR(4000) NULL,
	`AIC_PARAM_OLD_VALUE` NVARCHAR(4000) NOT NULL,
	`AIC_PARAM_VALUE` NVARCHAR(4000) NULL,
	`AIC_PARAM_DATETIME` DATETIME NULL,
	`AIC_PARAM_CANCELLED_DATETIME` DATETIME NULL,
	PRIMARY KEY (`AIC_PARAM_ACT_PK_ID`)
);

USE `results_db`;
DROP TABLE IF EXISTS `EXECUTEDACTIONS`;
CREATE TABLE `EXECUTEDACTIONS`(
	`AIEXEC_PARAM_PK_ID` INT NOT NULL AUTO_INCREMENT,
	`AIEXEC_PARAM_ADV_PK_ID` INT NULL,
	`AIEXEC_PARAM_ADVICE` NVARCHAR(4000) NULL,
	`AIEXEC_PARAM_NAME` NVARCHAR(4000) NULL,
	`AIEXEC_PARAM_OLD_VALUE` NVARCHAR(4000) NOT NULL,
	`AIEXEC_PARAM_VALUE` NVARCHAR(4000) NULL,
	`AIEXEC_PARAM_DATETIME` DATETIME NULL,
	`AIEXEC_PARAM_PROPOSED_VALUE` NVARCHAR(4000) NULL,
	`AIEXEC_PARAM_EXECUTED_DATETIME1` DATETIME NULL,
	PRIMARY KEY (`AIEXEC_PARAM_PK_ID`)
);
 
USE `results_db`;
DROP TABLE IF EXISTS `PARAMETER`;
CREATE TABLE `PARAMETER` (
	`PARAM_PK_ID` INT NOT NULL AUTO_INCREMENT,
	`PARAM_ADV_PK_ID` INT NULL,
	`PARAM_PROPOSED_VALUE` NVARCHAR(4000) NULL,
	`PARAM_OLD_VALUE` NVARCHAR(4000) NULL,
	`PARAM_VALUE` NVARCHAR(4000) NULL,
	`PARAM_NAME` NVARCHAR(4000) NULL,
	PRIMARY KEY (`PARAM_PK_ID`)
);