USE `results_db`;
DROP TABLE IF EXISTS `ADVICES`;
CREATE TABLE `ADVICES` (
	[AIP_ADV_PK_ID] [int] IDENTITY(1,1) NOT NULL,
	[AIP_ADV_DATETIME] [datetime] NULL,
	[AIP_ADV_ADVICE] [nvarchar](max) NULL,
	[AIP_ADV_PARAM_PROPOSED_VALUE] [nvarchar](max) NULL,
	[AIP_ADV_PARAM_OLD_VALUE] [nvarchar](max) NULL,
	[AIP_ADV_PARAM_NAME] [nvarchar](max) NULL,
 PRIMARY KEY (`AIP_ADV_PK_ID`)
 CONSTRAINT [PK_ADVICES] PRIMARY KEY CLUSTERED 
(
	[AIP_ADV_PK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

USE `results_db`;
DROP TABLE IF EXISTS `CANCELLEDACTIONS`;
CREATE TABLE `CANCELLEDACTIONS`(
	[AIC_PARAM_ACT_PK_ID] [int] IDENTITY(1,1) NOT NULL,
	[AIC_PARAM_ADV_PK_ID] [int] NULL,
	[AIC_PARAM_ADVICE] [nvarchar](max) NULL,
	[AIC_PARAM_NAME] [nvarchar](max) NULL,
	[AIC_PARAM_OLD_VALUE] [nvarchar](max) NOT NULL,
	[AIC_PARAM_VALUE] [nvarchar](max) NULL,
	[AIC_PARAM_DATETIME] [datetime] NULL,
	[AIC_PARAM_CANCELLED_DATETIME] [datetime] NULL,
 PRIMARY KEY (`AIC_PARAM_ACT_PK_ID`)
 CONSTRAINT [PK_ACTION] PRIMARY KEY CLUSTERED 
(
	[AIC_PARAM_ACT_PK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

USE `results_db`;
DROP TABLE IF EXISTS `EXECUTEDACTIONS`;
CREATE TABLE `EXECUTEDACTIONS`(
	[AIEXEC_PARAM_PK_ID] [int] IDENTITY(1,1) NOT NULL,
	[AIEXEC_PARAM_ADV_PK_ID] [int] NULL,
	[AIEXEC_PARAM_ADVICE] [nvarchar](max) NULL,
	[AIEXEC_PARAM_NAME] [nvarchar](max) NULL,
	[AIEXEC_PARAM_OLD_VALUE] [nvarchar](max) NOT NULL,
	[AIEXEC_PARAM_VALUE] [nvarchar](max) NULL,
	[AIEXEC_PARAM_DATETIME] [datetime] NULL,
	[AIEXEC_PARAM_PROPOSED_VALUE] [nvarchar](max) NULL,
	[AIEXEC_PARAM_EXECUTED_DATETIME1] [datetime] NULL,
 PRIMARY KEY (`AIEXEC_PARAM_PK_ID`)
 CONSTRAINT [PK_PARAMETERS] PRIMARY KEY CLUSTERED 
(
	[AIEXEC_PARAM_PK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

USE `results_db`;
DROP TABLE IF EXISTS `PARAMETER`;
CREATE TABLE `PARAMETER` (
	[PARAM_PK_ID] [int] IDENTITY(1,1) NOT NULL,
	[PARAM_ADV_PK_ID] [int] NULL,
	[PARAM_PROPOSED_VALUE] [nvarchar](max) NULL,
	[PARAM_OLD_VALUE] [nvarchar](max) NULL,
	[PARAM_VALUE] [nvarchar](max) NULL,
	[PARAM_NAME] [nvarchar](max) NULL,
 PRIMARY KEY (`PARAM_PK_ID`)
 CONSTRAINT [PK_PARAMETER] PRIMARY KEY CLUSTERED 
(
	[PARAM_PK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
