version: "3.9"
services:
  mysql-service:
    build: ./ai-proficient-mysql/
    image:  ai-proficient-mysql:1.0.0
    container_name: aip-mysql-1.0.0
    ports:
       - 3306:3306
    environment: 
       - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes: 
      - ${LOCAL_PATH}/service-MYSQL/mysql:/var/lib/mysql

  mysql-service-CROM-UL:
    build: ./ai-service-CROM/
    image: ai-proficient-mysql:CROM-1.0.0
    container_name: aip-mysql-CROM
    ports:
      - 3309:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes: 
      - ${LOCAL_PATH}/service-CROM/mysql:/var/lib/mysql

  mysql-service-EXDM-TK:
    build: ./ai-service-EXDM/
    image: ai-proficient-mysql:EXDM-1.0.0
    container_name: aip-mysql-EXDM
    ports:
       - 3305:3306
    environment: 
       - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes:
      - ${LOCAL_PATH}/service-EXDM/mysql:/var/lib/mysql

  mysql-service-EXSM-TK:
    build: ./ai-service-EXSM/
    image: ai-proficient-mysql:EXSM-1.0.0
    container_name: aip-mysql-EXSM
    ports:
       - 3304:3306
    environment: 
       - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes: 
       - ${LOCAL_PATH}/service-EXSM/mysql:/var/lib/mysql
  
  mysql-service-FCIR-TF:
    build: ./ai-service-FCIR/
    image: ai-proficient-mysql:FCIR-1.0.0
    container_name: aip-mysql-FCIR
    ports:
       - 3303:3306
    environment: 
       - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes: 
       - ${LOCAL_PATH}/service-FCIR/mysql:/var/lib/mysql

  mysql-service-GHO-IMP:
    build: ./ai-service-GHO/
    image: ai-proficient-mysql:GHO-1.0.0
    container_name: aip-mysql-GHO
    ports:
       - 3302:3306
    environment: 
       - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes: 
       - ${LOCAL_PATH}/service-GHO/mysql:/var/lib/mysql

  mysql-service-NRPD-UL:
    build: ./ai-service-NRPD/
    image: ai-proficient-mysql:NRPD-1.0.0
    container_name: aip-mysql-NRPD
    ports:
       - 3311:3306
    environment: 
       - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes: 
       - ${LOCAL_PATH}/service-NRPD/mysql:/var/lib/mysql

  mysql-service-NRPP-UL:
    build: ./ai-service-NRPP/
    image: ai-proficient-mysql:NRPP-1.0.0
    container_name: aip-mysql-NRPP
    ports:
       - 3312:3306
    environment: 
       - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes: 
       - ${LOCAL_PATH}/service-NRPP/mysql:/var/lib/mysql

  mysql-service-SDDM-IMP:
    build: ./ai-service-SDDM/
    image: ai-proficient-mysql:SDDM-1.0.0
    container_name: aip-mysql-SDDM
    ports:
       - 3313:3306
    environment: 
       - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes: 
       - ${LOCAL_PATH}/service-SDDM/mysql:/var/lib/mysql

  mysql-service-SPAA-ATC:
    build: ./ai-service-SPAA/
    image: ai-proficient-mysql:SPAA-1.0.0
    container_name: aip-mysql-SPAA
    ports:
       - 3314:3306
    environment: 
       - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes: 
       - ${LOCAL_PATH}/service-SPAA/mysql:/var/lib/mysql

  mysql-service-BWD-TEK:
    build: ./ai-service-BWD-TEK/
    image: ai-proficient-mysql:BWD-1.0.0
    container_name: aip-mysql-BWD
    ports:
       - 3307:3306
    environment: 
       - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes: 
       - ${LOCAL_PATH}/service-BWD/mysql:/var/lib/mysql

  mysql-service-BWP-TEK:
    build: ./ai-service-BWP-TEK/
    image: ai-proficient-mysql:BWP-1.0.0
    container_name: aip-mysql-BWP
    ports:
       - 3308:3306
    environment: 
       - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes: 
       - ${LOCAL_PATH}/service-BWP/mysql:/var/lib/mysql


