USE results_db;
DROP TABLE IF EXISTS results_table;

CREATE TABLE results_table (
  id INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id),
  Usage  BOOLEAN DEFAULT FALSE,
  Date   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);